name: game_demo
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flame_tiled: ^3.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/tiles/
    - assets/fonts/
